### PR TITLE
Add support for coma separated ignore (--ignore=123,456) 

### LINKED ISSUE #341: Let 'ignore' take a list of coma separated ID
As it is now, in case we want to ignore multiple vulnerabilities, we have to use
`safety check -i 1234 -i 4567 -i 89101`

I'd like to suggest to start supporting coma separated list in a similar fashion as well known similar tools are doing (flake8, pylint, etc)

`safety check -i 1234,4567,89101`

Would you welcome a PR?

### PR DESCRIPTION
**Pull request by bagerard**
Fixes #341

This adds support for providing ignore as `--ignore=123,456`

The previous format `--ignore=123 --ignore=456` is still supported for backward compatilibity, I guess you don't want to introduce a breaking change here.

Let me know if there is anything I should fix in the PR.

### CODE REVIEW

**Comment by bagerard** [comment]
Any update on this?

**Comment by bagerard** [comment]
Hi, sorry to insist but is there any chance to get it merged?

**Comment by yeisonvargasf** [comment]
Hi @bagerard, thanks for this PR! Yes, we have a coming version of Safety, I expect to merge this PR after the new 2.0 release. I'm sorry for don't reply with an update in this PR before.

**Comment by bagerard** [comment]
Alright no problem, thanks for the feedback :+1:

**Comment by bagerard** [comment]
Just fixed this PR, there were lots of conflict with recent changes, let me know if anything else is needed

**Review by yeisonvargasf — APPROVED** [review]
Thank you @bagerard!

**Pull request merged**
