### PR TITLE
Packaging improvements

### PR DESCRIPTION
**Pull request by GhostofGoes**
- Use 'io' package as a more reliable way of opening files
on Windows in Python 2.7
- Add python_requires, which helps pip determine if the
package is compatible with the version of Python.
- Change development status to "Production/Stable" in PyPI classifiers
- Cleanup and formatting of setup.py

### CODE REVIEW

**Comment by GhostofGoes** [comment]
Fixed development status and removed `test_suite`.

`python_requires` is already set to 2.7 and 3.5+. Did you want to explicitly exclude 3.9 and newer?

**Comment by GhostofGoes** [comment]
Crap, messed up the merge (tried a rebase and PyCharm balked). I'll try to clean up this mess...

**Comment by GhostofGoes** [comment]
Well, after some research I'm at a loss at how to fix this without deleting the fork/branch and making a new PR. Any ideas?

Sorry about this, I'm not used to rebasing PRs (or rebasing in general).

**Comment by rafaelpivato** [comment]
No problem, @GhostofGoes -- I will try to get your changes locally later this week and see if I can help you cleaning this.

**Comment by rafaelpivato** [comment]
@GhostofGoes I will not have available time as soon as I would like to fix this. Would it be possible for you to re-submit your changes in another clean branch in a separate pull-request, please?

**Comment by GhostofGoes** [comment]
Sure thing

**Pull request closed without merging**
