### PR TITLE
fix UnicodeDecodeError: 'ascii' codec #22

### PR DESCRIPTION
**Pull request by maratsh**
fix UnicodeDecodeError: 'ascii' codec can't decode byte

### CODE REVIEW

**Comment by jayvdb** [comment]
@maratsh , could you rebase please.
This line has been moved to
https://github.com/pyupio/safety/blame/master/safety/formatter.py#L116

**Comment by maratsh** [comment]
You're welcome :)

**Comment by jayvdb** [comment]
Thanks!

`test_check_live` had a `ConnectTimeout` on Travis.
I assume restarting the job will fix it.

**Comment by Jwomers** [comment]
@maratsh this is looking good, going to merge this now.

**Pull request merged**
