### PR TITLE
Simplify Dockerfilei386 by using i386/python base image

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Use `i386/python:3.6-slim` instead of `i386/ubuntu:18.04`, save the time and network bandwidth to install python, also align to Dockerfile(`python:3.6-slim`), make the environment more consistent, also save the disk space and image size:
```
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
new                           latest              a163d1c2dd4d        About an hour ago   161MB
old                           latest              1a5e52fb3e2e        11 minutes ago      485MB
```

### CODE REVIEW

**Comment by rafaelpivato** [comment]
We use the docker image to build some binaries via AppVeyor. If you could please check the errors for the failing check, that would be helpful.

Your point on reducing file size is awesome.

**Comment by PeterDaveHello** [comment]
I didn't notice that AppVeyor will be affected, will take a look and see how to deal with it.

**Comment by PeterDaveHello** [comment]
Looks like the `binutils` package is missing, I'll see not using slim image or install it manually, which one is better here.
https://pyinstaller.readthedocs.io/en/stable/requirements.html#gnu-linux

**Comment by PeterDaveHello** [comment]
@rafaelpivato should be fixed now!

**Review by rafaelpivato — APPROVED** [review]
Thanks for this. Binary should be much smaller now.

**Pull request merged**
